### ISSUE TITLE
Add Binance

### ISSUE THREAD

**Issue by jainanuj7** [mobnetic/BitcoinChecker#493] opened 2017-11-20 20:45 UTC
www.binance.com
Add this exchange.
They have a couple of unique alt coins listed like Power Ledger(rose 65% today, check it out!)

**Comment by lazygeek7** [comment] 2017-11-20 20:49
Oops, looks like binance thread was already marked as duplicate a few days back.
Sorry.
Anyways where is the original thread regarding "binance"?

**Comment by rhkarls** [comment] 2017-11-23 17:50
https://github.com/mobnetic/BitcoinChecker/issues/433

**Comment by mrboard** [comment] 2017-11-26 21:36
Bittrex has been the top volume exchange for most altcoins, but they are getting hacked/suspending accounts left and right. Many are moving to Binance. I love your app, but it is missing a key exchange. Please add it asap. It is a bigger and more popular exchange than many of random exchanges that you do have listed.

**Closed** 2017-12-24 07:57 UTC
Labels: duplicate

**Comment by MaciejCiemiega** [comment] 2017-12-26 09:09
Duplicate of https://github.com/mobnetic/BitcoinChecker/issues/433
