### ISSUE TITLE
Binance 

### ISSUE THREAD

**Issue by jayesh1306** [mobnetic/BitcoinChecker#611] opened 2018-01-01 07:12 UTC
Add binance cryptocurrency exchange

**Comment by the3dmen** [comment] 2018-01-01 23:14
I agree

**Comment by XxionxX** [comment] 2018-01-01 23:32
I would also like this exchange please. Do we need to donate?

**Comment by Silverspark75** [comment] 2018-01-01 23:33
hoping binance will help

**Comment by lethalbrains** [comment] 2018-01-02 09:26
Binance is a major exchange. Must be added.

**Comment by PaulioArmani** [comment] 2018-01-02 15:02
I agree, please add binance

**Comment by RJC73** [comment] 2018-01-02 23:35
I agree. Please add Binance. Have given your app 5-stars.

**Comment by ktopcuoglu** [comment] 2018-01-03 12:11
Binance required.

**Comment by rahilpathan** [comment] 2018-01-04 00:56
I agree, Binance necessary

**Comment by MaciejCiemiega** [comment] 2018-01-04 08:29
Duplicate of https://github.com/mobnetic/BitcoinChecker/issues/433

**Closed by MaciejCiemiega** 2018-01-04 08:29 UTC
