### ISSUE TITLE
PLEASE add BINANCE exchange

### ISSUE THREAD

**Issue by robertbigk** [mobnetic/BitcoinChecker#605] opened 2017-12-30 07:26 UTC
Wow program is best off The best . Please be do kind and add binance exchange

**Comment by xekius** [comment] 2017-12-30 09:04
Yes please add binance, this app is one of the best I ever came across.

**Comment by andreivoinea93** [comment] 2017-12-30 17:54
+1

**Comment by chaitanyapotti** [comment] 2017-12-31 06:30
+1

**Comment by Xyic0re** [comment] 2017-12-31 12:16
+1

**Comment by Mj11048** [comment] 2017-12-31 17:37
Pretty please add github

**Comment by xdslx** [comment] 2017-12-31 18:32
Isnt there anyone to add BINANCE for the Bitcoin Checker

**Comment by nelson777** [comment] 2017-12-31 23:31
+1

**Comment by RichyHBM** [comment] 2018-01-01 14:40
Hopefully I may have some spare time soon to add it!

**Comment by rastoha** [comment] 2018-01-03 14:28
+1 Many thanks. Now that Bittrex temporarily doesnt approves new members, Binance is becoming the major altcoin exchange.

**Comment by MaciejCiemiega** [comment] 2018-01-04 08:28
Duplicate of https://github.com/mobnetic/BitcoinChecker/issues/433

**Closed by MaciejCiemiega** 2018-01-04 08:28 UTC
