### ISSUE TITLE
Can you include Binance.com exchange prices

### ISSUE THREAD

**Issue by nick-g4golf** [mobnetic/BitcoinChecker#623] opened 2018-01-04 20:18 UTC

**Comment by cad0p** [comment] 2018-01-04 23:28
Me too!

**Comment by carlos-ballester** [comment] 2018-01-05 07:49
Yes please, add binance exchange (which by the way is the biggest exchange right now in terms of volume)

**Comment by begrossi** [comment] 2018-01-05 15:20
+1 to Binance

**Comment by unklejo** [comment] 2018-01-06 00:12
+1 Binance please.

**Comment by jasonnm** [comment] 2018-01-06 09:38
Yes please!

**Comment by jammyto10** [comment] 2018-01-06 10:39
How do I add binnacle.com please

**Comment by Guruleenyc** [comment] 2018-01-06 16:34
Plus one. This would be great since it's the leading exchange. Thank you in advance.

**Comment by MaciejCiemiega** [comment] 2018-01-06 21:09
Duplicate of https://github.com/mobnetic/BitcoinChecker/issues/433

**Closed by MaciejCiemiega** 2018-01-06 21:09 UTC
Labels: duplicate
