### ISSUE TITLE
Please Add Binance

### ISSUE THREAD

**Issue by khea7en** [mobnetic/BitcoinChecker#594] opened 2017-12-26 16:14 UTC
Hello, 
I know any users would appreciate the addition of Binance as it has a very high trading volume. Please add to list of source information
Thank you

**Comment by savedlikebobross** [comment] 2017-12-26 21:09
Came here to say this also.

**Comment by MaciejCiemiega** [comment] 2017-12-27 09:21
Duplicate of #433

**Closed by MaciejCiemiega** 2017-12-27 09:21 UTC
Labels: duplicate
